MoniMate/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('core.urls')),
    path('',include('expense.urls')),
    path('glossary/', TemplateView.as_view(template_name="glossary.html"), name='glossary'),
    path('assets/',include('assets.urls')),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'core'

urlpatterns = [
    path('login/',views.login_view, name='login'),
    path('register/', views.register_view,name='register'),
    path('logout/',views.logout_view,name='logout'),

    #password reset views
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='core/password_reset.html'),name='password_reset'),
    path('password_reset_done/',auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'),name='password_reset_complete'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_approved = models.BooleanField(default=False) # approve status
    notify_email = models.EmailField(blank=True, null=True) # notification email
    inflation = models.FloatField(default=10) #inflation %

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import UserProfile
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings

def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False # prevents login until approval
            user.save()
            messages.success(request, "Account created successfully. Wait for the approval.")

            # collect notify email 
            UserProfile.objects.create(user=user, notify_email = request.POST.get('notify_email'))

            # Notify admin
            send_mail(
                'New Signup Request - Moni-Mate',
                f'A new user "{user.username}" has signed up and is awaiting approval.',
                settings.DEFAULT_FROM_EMAIL,
                ['freelance.blackfly123@gmail.com']
            )
            return render(request, 'core/signup_processing.html') # request being processed page.
    else:
        form = UserCreationForm()
    return render(request, 'core/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('expense:dashboard')
        else:
            messages.error(request, "Invalid credentials")
    else:
        form = AuthenticationForm()
    return render(request, 'core/login.html', {'form': form})

@login_required
def logout_view(request):
    logout(request)
    messages.info(request, "Logged out successfully")
    return redirect('core:login')

core/templates/core/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'core/css/style.css' %}?v=4">
<div class="auth-container">
    <h2>Login to Your Account</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
    <p>forgot password? <a style="color: brown;" href="{% url 'core:password_reset' %}">Reset Password</a></p>
    <p>Don't have an account? <a style="color: brown;" href="{% url 'core:register' %}">Sign Up</a></p>
</div>
{% endblock %}

core/templates/core/password_reset.html
{% extends "base.html" %}
{% block title %}Password Reset{% endblock %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'core/css/style.css' %}">
<div class="auth-container">
    <h2>Reset Your Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Send Reset Link</button>
    </form>
</div>
{% endblock %}

core/templates/core/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Password Reset Complete{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'core/css/style.css' %}">
<div class="auth-container">
    <h2>Password Reset Successful</h2>
    <p>You can now <a href="{% url 'core:login' %}">log in</a> with your new password.</p>
</div>
{% endblock %}

core/templates/core/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Confirm New Password{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'core/css/style.css' %}">
<div class="auth-container">
    <h2>Set a New Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Set New Password</button>
    </form>
</div>
{% endblock %}

core/templates/core/password_reset_done.html
{% extends "base.html" %}
{% block title %}Password Reset Sent{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'core/css/style.css' %}">
<div class="auth-container">
    <h2>Password Reset Link Sent</h2>
    <p>Please check your email for further instructions.</p>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'core/css/style.css' %}?v=3">
<div class="auth-container">
    <h2>Create a New Account</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <label for="notify_email">Email:</label>
        <input type="email" name="notify_email" required>
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
</div>
{% endblock %}

core/templates/core/signup_processing.html
{% extends 'base.html' %}
{% block title %}Account Processing{% endblock %}
{% block content %}
<h2>Your signup request is being processed.</h2>
<p>You will be notified via email once approved or rejected.</p>
<style>
    h2, p {
        text-align: center;
    }
</style>
{% endblock %}