MoniMate/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('core.urls')),
    path('',include('expense.urls')),
    path('glossary/', TemplateView.as_view(template_name="glossary.html"), name='glossary'),
    path('assets/',include('assets.urls')),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'core'

urlpatterns = [
    path('login/',views.login_view, name='login'),
    path('register/', views.register_view,name='register'),
    path('logout/',views.logout_view,name='logout'),

    #password reset views
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='core/password_reset.html'),name='password_reset'),
    path('password_reset_done/',auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'),name='password_reset_complete'),
]

expense/urls.py
from django.urls import path
from . import views


app_name = 'expense'

urlpatterns = [
    path('',views.dashboard,name='dashboard'),
    path('expense/',views.add_expense,name='add_expense'),
    path('history/',views.expense_history,name='expense_history'),
    path('income/',views.add_income,name='add_income'),
    path('payments/',views.payment_methods,name='payment_methods'),
    path('payments/delete/<int:pk>/',views.delete_payment_method,name='delete_payment_method'),
    path('expense/delete/<int:pk>/',views.delete_expense,name='delete_expense'),
    path('settings/',views.settings,name='settings'),
]

expense/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User


class PaymentMethod(models.Model):
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=20, choices=[
        ('bank','Bank'),
        ('credit_card', 'Credit Card'),
        ('digital_wallet', 'Digital Wallet'),
        ('cash','Cash'),
    ])
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True)
    spent_limit = models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True) # credit card spent limit in amounts.
    original_credit_limit = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True) # used to reset credit limit value to normal upon billing cycle completion.
    credit_limit = models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True) #for credit cards -enter total amount limit.
    billing_date = models.IntegerField(default=1) # billing date for the credit card ( credit cards only )
    minimum_balance = models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True,help_text="  Enter 0 for Zero Balance Accounts.") #for banks - default = 10%
    account_type = models.CharField(max_length=50,null=True,blank=True) #banks


    def __str__(self):
        return f'{self.name} ({self.get_type_display()})'

class Expense(models.Model):
    TRANSACTION_MODE = [
        ('debit_card','Debit Card'),
        ('mobile_wallets','Mobile Wallets'),
        ('upi','UPI'),
        ('net_banking','Net Banking'),
        ('neft','NEFT'),
        ('imps','IMPS'),
        ('other','Other'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField(default=now)
    payment_method = models.ForeignKey(PaymentMethod,null=True,blank=True, on_delete=models.SET_NULL)
    transaction_mode = models.CharField(max_length=100,choices=TRANSACTION_MODE,default='other')
    category = models.CharField(max_length=10,choices=[
        ('needs','Needs'),
        ('wants','Wants'),
        ('savings','Savings'),
        ('income','Income'),
    ], default='needs')

    def save(self,*args, **kwargs):
        #update the balance or limit based on the payment method & category type

        if self.payment_method:
            if self.payment_method.type == 'credit_card':
                if self.category != 'income': #cannot add income to credit cards.
                    self.payment_method.credit_limit -= self.amount
                else:
                    return None
            else:
                if self.category == 'income':
                    self.payment_method.balance += self.amount
                else:
                    self.payment_method.balance -= self.amount
            self.payment_method.save()
        super().save(*args, **kwargs)


    def __str__(self):
        return f'{self.name} = {self.amount}'

expense/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.utils.safestring import mark_safe
import json, io, calendar
from collections import defaultdict
from django.utils.timezone import now
from django.contrib import messages
from assets.models import Asset, Liabilities
from datetime import datetime
from .support_func import generate_pdf
from django.http import HttpResponse
from core.models import UserProfile
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponseForbidden

# SUPPORT FUNCTIONS ---
def hosting_alert():
    # Date as a string
    date_str = "2025-04-04" # update date here ( 2 days before actual date )
    given_date = datetime.strptime(date_str, "%Y-%m-%d").date()
    if datetime.now().date() == given_date:
        send_mail(
            'Update Hosting Plan Date - MoniMate (Admin)',
            'Dear Admin\n,Please update the hosting plan date by visiting "pythonanywhere" website. Also update the next reminder date in the "expense>views.py(file)>hosting_alert(function)".\nRegards,\nMoniMate Team',
            settings.DEFAULT_FROM_EMAIL,
            ['freelance.blackfly123@gmail.com'],
            fail_silently = True,
        )

def reset_credit_limit(user): # function to reset credit_card billing cycle
    payment_methods = PaymentMethod.objects.filter(user=user,type='credit_card')
    today = now().date()

    if today.day == 1: # 1st day of month
        for method in payment_methods:
            if method.original_credit_limit is not None:
                method.credit_limit = method.original_credit_limit
                method.save()
# calculate asset-liability ratio
def networth_ratio(request):
    assets = Asset.objects.filter(user = request.user)
    liabilities = Liabilities.objects.filter(user = request.user)
    networth_value = [float(sum(asset.current_value for asset in assets)),float(sum(lib.total_amount for lib in liabilities ))]
    networth_labels = ['Assets','Liabilites']
    return networth_labels,networth_value

def billing_due(date):
    if date == datetime.now().day:
        return True
    else:
        return False

def monthly_report(request,month,year):
    expenses = Expense.objects.filter(user = request.user,date__month = month,date__year = year).order_by('date')
    row_data = []
    needs,wants,savings,total_spending = 0,0,0,0
    if expenses:
        for expense in expenses:
            row_data.append({'name':expense.name,'category':expense.get_category_display(),'amount':str(expense.amount),'date':str(expense.date),'payment_method':expense.payment_method.name,'transaction_mode':expense.get_transaction_mode_display()})

            if expense.category != 'income':
                total_spending += expense.amount
            # categorizing expense
            if expense.category == 'needs':
                needs += expense.amount
            elif expense.category == 'wants':
                wants += expense.amount
            elif expense.category == 'savings':
                savings += expense.amount
        # ratio calculation
        if total_spending > 0:
            if needs > 0:
                need_rat = round((needs/total_spending)*100,2)
            else:
                need_rat = 0
            if wants > 0:
                want_rat = round((wants/total_spending)*100,2)
            else:
                want_rat = 0
            if savings > 0:
                saving_rat = round((savings/total_spending)*100,2)
            else:
                saving_rat = 0
        summary = {
            'Total Needs':f'{needs} ({need_rat}%)',
            'Total Wants':f'{wants} ({want_rat}%)',
            'Total Savings':f'{savings} ({saving_rat}%)',
            'Total Spending':total_spending
        }
        return row_data,summary
    else:
        return None,None

#-----------------------

@login_required
def dashboard(request):
    start_of_month = now().replace(day=1)
    # print(f'start of month {start_of_month}')
    expenses = Expense.objects.filter(user=request.user,date__gte=start_of_month).exclude(category='income').order_by('-date')
    payment_methods = PaymentMethod.objects.filter(user=request.user)


    # initializing warnings
    warnings = []

    # payment method balance warnings
    for method in payment_methods:
        if method.type == 'cash':
            if method.balance < 100:
                warnings.append('Your wallet is low on cash, withdraw cash from nearby ATM.')
            continue
        if method.type == 'credit_card' and billing_due(method.billing_date):
            warnings.append(f'Reminder: Today is the billing day for your credit card - {method.name}')
        if method.type == 'credit_card' and method.credit_limit is not None:
            # calculating current spent ammount for credit card
            spend_amount = method.original_credit_limit - method.credit_limit
            if spend_amount >= method.spent_limit:
                warnings.append(f'Amount spend for {method.name} has reached/crossed the safe limit!')
        if method.balance is not None:
            if method.balance < method.minimum_balance:
                warnings.append(f'Balance for {method.name} is below minimum required!')


    # reset credit limit if its start of a new month
    reset_credit_limit(request.user)
    # total expenses ( current month)
    total_expense = expenses.aggregate(overall_total=Sum('amount'))['overall_total']
    # calculate category-wise totals
    category_totals = expenses.values('category').annotate(total=Sum('amount')).order_by('category')
    category_labels = [entry['category'].capitalize() for entry in category_totals]
    category_values = [float(entry['total']) for entry in category_totals]

    balances = {}

    for method in payment_methods: # Display account balances
        if method.type == 'credit_card':
            balances[method.name] = method.credit_limit
        else:
            balances[method.name] = method.balance

    # networth ratio
    networth_labels,networth_values = networth_ratio(request)
    print(networth_values,networth_labels)
    context = {
        'balances': balances,
        'category_labels':json.dumps(category_labels),
        'category_values':json.dumps(category_values) if category_values else None,
        'total_expense':total_expense if total_expense else 0,
        'payment_methods':payment_methods,
        'warnings':warnings,
        'networth_labels':networth_labels,
        'networth_values':networth_values if networth_values else None,
    }
    # print(type(balances))
    return render(request, 'expense/dashboard.html',context)

@login_required
def add_expense(request):
    if request.method == 'POST':
        form = ExpenseForm(request.POST, user=request.user)
        if form.is_valid():
            expense = form.save(commit=False)
            expense.user = request.user
            expense.save()
            return redirect('expense:dashboard')
    else:
        form = ExpenseForm(user=request.user)
    return render(request,'expense/add_expense.html',{'form':form})

@login_required
def expense_history(request):
    # current date and time
    present = now()
    start_of_month = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    expenses = Expense.objects.filter(user=request.user,date__gte = start_of_month).order_by('-date')
    return render(request, 'expense/expense_history.html',{'expenses':expenses})

@login_required
def add_income(request):
    if request.method == 'POST':
        form = IncomeForm(request.POST, user=request.user)
        if form.is_valid():
            income = form.save(commit=False)
            income.user = request.user
            income.save()
            return redirect('expense:dashboard')
    else:
        form = IncomeForm(user=request.user)
    return render(request,'expense/add_income.html',{'form':form})

@login_required
def payment_methods(request):
    payment_method = PaymentMethod.objects.filter(user=request.user)

    warnings = []

    # payment method balance warnings
    for method in payment_method:
        if method.type == 'cash':
            if method.balance < 100:
                warnings.append('Your wallet is low on cash, withdraw cash from nearby ATM.')
            continue
        if method.type == 'credit_card' and billing_due(method.billing_date):
            warnings.append(f'Reminder: Today is the billing day for your credit card - {method.name}')
        if method.type == 'credit_card' and method.credit_limit is not None:
            # calculating current spent ammount for credit card
            spend_amount = method.original_credit_limit - method.credit_limit
            if spend_amount >= method.spent_limit:
                warnings.append(f'Amount spend for {method.name} has reached/crossed the safe limit!')
        if method.balance is not None:
            if method.balance < method.minimum_balance:
                warnings.append(f'Balance for {method.name} is below minimum required!')

    # handle form submission
    if request.method == 'POST':
        form = PaymentMethodForm(request.POST)
        if form.is_valid():
            payment_method_form = form.save(commit=False)
            payment_method_form.user = request.user
            payment_method_form.save()
            return redirect('expense:payment_methods')
    else:
        form = PaymentMethodForm()

    context = {
        'payment_methods':payment_method,
        'warnings':warnings,
        'form':form,
    }
    return render(request,'expense/payment_methods.html', context)


expense/templates/expense/add_expense.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'expense/css/add_expense.css' %}?v=3">
<div class="form-container">
    <h2>Add Expense</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add Expense</button>
        <a href="{% url 'expense:dashboard' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>


<style>
    .form-container {
        width: 50%;
        margin: 0 auto;
        background-color: #333;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
    }

    h2 {
        text-align: center;
        color: #f9f9f9;
    }

    form {
        display: flex;
        flex-direction: column;
    }

    .btn {
        margin-top: 10px;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .btn-primary {
        background-color: #28a745;
        color: #fff;
    }

    .btn-primary:hover {
        background-color: #218838;
    }

    .btn-secondary {
        background-color: #c40808;
        color: #fff;
        text-align: center;
    }

    .btn-secondary:hover {
        background-color: #9c0808;
    }
</style>
{% endblock %}

expense/templates/expense/add_income.html
{% extends 'base.html' %}
{% block content %}

<div class="form-container">
    <h2>Add Income</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add Income</button>
        <a href="{% url 'expense:dashboard' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>

<style>
    .form-container {
        width: 50%;
        margin: 0 auto;
        background-color: #333;
        color:#724fff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
    }

    h2 {
        text-align: center;
        color:#724fff;
    }

    form {
        display: flex;
        flex-direction: column;
    }

    .btn {
        margin-top: 10px;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }

    .btn-secondary {
        background-color: #c40808;
        color: #fff;
        text-align: center;
    }

    .btn-secondary:hover {
        background-color: #9c0808;
    }
    
    .form-control {
        background-color: #1c1c1c; /* Dark background */
        color: white; /* White text for readability */
        border: 1px solid #287d10; /* Match your theme color */
        border-radius: 5px; /* Rounded edges */
        padding: 10px; /* Add some padding */
        font-size: 1em; /* Adjust text size */
        outline: none; /* Remove default focus outline */
    }

    /* Change color on focus */
    .form-control:focus {
        border-color: #724fff; /* Highlight with another theme color */
        box-shadow: 0 0 5px #724fff; /* Optional glow effect */
    }
</style>

{% endblock %}

expense/templates/expense/confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="confirm-delete">
    <h2>Are you sure you want to delete "{{ payment_method.name }}"?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
        <a href="{% url 'payment_methods' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
<style>
    .btn-secondary {
    background-color: #6c757d;
    color: white;
    border: none;
    padding: 8px 12px;
    border-radius: 4px;
    cursor: pointer;
    }

    .btn-secondary:hover {
    background-color: #5a6268;
    }
</style>
{% endblock %}

expense/templates/expense/expense_history.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'expense/css/style.css' %}?v=1">
<div class="expense-history">
    <h2 style="text-align: center; color: #724fff;" >Expense History</h2>
    <table>
        <thead>
            <tr>
                <th>Expense</th>
                <th>Amount</th>
                <th>Date</th>
                <th>Category</th>
                <th>Payment Method</th>
                <th>Transaction Mode</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for expense in expenses %}
            <tr>
                <td>{{ expense.name }}</td>
                <td>{{ expense.amount }}</td>
                <td>{{ expense.date }}</td>
                <td>{{ expense.get_category_display }}</td>
                <td>{{ expense.payment_method }}</td>
                <td>{{ expense.get_transaction_mode_display }}</td>
                <td><form method="post" action="{% url 'expense:delete_expense' expense.id %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<style>
    .expense-history table {
        width:100%;
        border-collapse: collapse;
    }

    .expense-history th {
        background-color: #5a5959;
        border: 1px solid #555;
        padding: 8px;
        text-align: left;
        color:#000;
    }

    .expense-history td {
        border: 1px solid #555;
        padding: 8px;
        text-align: left;
        color:white;
    }

    .btn-danger {
        background-color: #dc3545;
        color: white;
        border: none;
        padding: 8px 12px;
        border-radius: 4px;
        cursor: pointer;
    }

    .btn-danger:hover {
        background-color: #c82333;
    }

</style>
{% endblock %}

expense/templates/expense/payment_methods.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'expense/css/payment_methods.css' %}?v=5">
<script src="{% static 'expense/js/payment_methods.js' %}?v=9"></script>

<div class="payment-methods">
    <h2>Payment Methods</h2>

    <!-- Display Warnings -->
    {% if warnings %}
        <div class="warnings">
            {% for warning in warnings %}
                <p class="warning">{{ warning }}</p>
            {% endfor %}
        </div>
    {% endif %}

    <!-- List of Payment Methods -->
    <div class="payment-method-list">
        {% for method in payment_methods %}
            <div class="payment-method">
                <h3>{{ method.name }}</h3>
                {% if method.type == 'bank' %}
                    <p>Type: {{ method.get_type_display }}</p>
                    <p>Balance: ₹{{ method.balance|default:"0" }}</p>
                    <p>Minimum Balance: ₹{{ method.minimum_balance|default:"--" }}</p>
                    <p>Account Type: {{ method.account_type|default:"--" }}</p>
                {% elif method.type == 'credit_card' %}
                    <p>Type: {{ method.get_type_display }}</p>
                    <p>Credit Limit: ₹{{ method.credit_limit }}</p>
                    <p>Spent Limit: ₹{{ method.spent_limit }}</p>
                    <p>Billing Date: {{ method.billing_date }}<br><sub style="color: #ff8503;">Credit balance resets on this date.</sub></p>
                {% else %}
                    <p>Type: {{ method.get_type_display }}</p>
                    <p>Balance: ₹{{ method.balance|default:"0" }}</p>
                {% endif %}

                <form method="post" action="{% url 'expense:delete_payment_method' method.id %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        {% endfor %}
    </div>

    <!-- Add/Edit Payment Method Form -->
    <div class="payment-method-form">
        <h3>Add Payment Method</h3>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Save</button>
        </form>
    </div>
</div>
<style>
    .btn-danger {
    background-color: #dc3545;
    color: white;
    border: none;
    padding: 8px 12px;
    border-radius: 4px;
    cursor: pointer;
}

.btn-danger:hover {
    background-color: #c82333;
}

</style>
{% endblock %}

expense/templates/expense/settings.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Settings{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'expense/css/settings.css' %}?v=1">

<div class="container">
    <header>
        <h1>{{ username }}</h1>
    </header>

    <section class="asset-details">
        <p><strong>Email:</strong> {{ email }}</p>
        <p><strong>Inflation:</strong> {{ inflation }}</p>
    </section>

    <section class="update-section">
        <h3>Update Inflation</h3>
        
        <form method="post" action="{% url 'expense:settings' %}">
            {% csrf_token %}
            <input type="hidden" name="form_type" value="inflation-form">

            <label for="new-value">New Value:</label>
            <input type="number" name="new-value" id="new-value" required>

        <button type="submit" class="btn btn-primary">Update Inflation</button>
        </form>
    </section>

    <section class="update-section">
        <h3>Generate Expense Report</h3>
        
        <form method="post" action="{% url 'expense:settings' %}">
            {% csrf_token %}
            <input type="hidden" name="form_type" value="expense-report">
            <label for="report-type">Report Type:</label>
            <select id="report-type" name="report-type">
                <option value="monthly">Monthly</option>
                <option value="yearly">Yearly</option>
            </select>
            <label for="year">Year:</label>
            <input type="number" name="year" id="year" required>
            <label for="month">Month:</label>
            <select id="month" name="month">
                <option value="January">January</option>
                <option value="February">February</option>
                <option value="March">March</option>
                <option value="April">April</option>
                <option value="May">May</option>
                <option value="June">June</option>
                <option value="July">July</option>
                <option value="August">August</option>
                <option value="September">September</option>
                <option value="October">October</option>
                <option value="November">November</option>
                <option value="December">December</option>
            </select>        

        <button type="submit" class="btn btn-primary">Generate Report</button>
        </form>
    </section>
</div>
{% endblock %}