MoniMate/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('core.urls')),
    path('',include('expense.urls')),
    path('glossary/', TemplateView.as_view(template_name="glossary.html"), name='glossary'),
    path('assets/',include('assets.urls')),
]

assets/urls.py
from django.urls import path
from . import views

app_name = 'assets'

urlpatterns = [
    path('',views.balance_sheet,name='wealth'),
    path('add-assets/',views.add_asset,name='add-assets'),
    path('asset-view/<int:asset_id>',views.asset_view,name='asset-view'),
    path('asset-delete/<int:pk>',views.delete_asset,name='delete-asset'),
    path('lib-view/<int:lib_id>',views.liability_view,name='lib-view'),
    path('add-liability/',views.add_liability,name='add-lib'),
    path('lib-delete/<int:pk>',views.delete_lib,name='delete-lib'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'core'

urlpatterns = [
    path('login/',views.login_view, name='login'),
    path('register/', views.register_view,name='register'),
    path('logout/',views.logout_view,name='logout'),

    #password reset views
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='core/password_reset.html'),name='password_reset'),
    path('password_reset_done/',auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'),name='password_reset_complete'),
]

expense/urls.py
from django.urls import path
from . import views


app_name = 'expense'

urlpatterns = [
    path('',views.dashboard,name='dashboard'),
    path('expense/',views.add_expense,name='add_expense'),
    path('history/',views.expense_history,name='expense_history'),
    path('income/',views.add_income,name='add_income'),
    path('payments/',views.payment_methods,name='payment_methods'),
    path('payments/delete/<int:pk>/',views.delete_payment_method,name='delete_payment_method'),
    path('expense/delete/<int:pk>/',views.delete_expense,name='delete_expense'),
    path('settings/',views.settings,name='settings'),
]

assets/models.py
from django.db import models
from django.contrib.auth.models import User

class Asset(models.Model):
    TYPE_CHOICES = [
        ('gold', 'Gold'),
        ('silver', 'Silver'),
        ('stocks', 'Stocks'),
        ('debt_mf', 'Debt MF'),
        ('equity_mf', 'Equity MF'),
        ('hybrid_mf', 'Hybrid MF'),
        ('other_mf', 'Other MF'),
        ('real_estate', 'Real Estate'),
        ('fixed_deposit', 'Fixed Deposit'),
        ('others', 'Others'),
    ]
    TENURE_CHOICES = [
        ('short_term', 'Short Term'),
        ('long_term', 'Long Term'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=100, choices=TYPE_CHOICES)
    tenure = models.CharField(max_length=50,choices=TENURE_CHOICES)
    purpose = models.CharField(max_length=255)
    invested_value = models.DecimalField(max_digits=12, decimal_places=2)
    current_value = models.DecimalField(max_digits=12,decimal_places=2)
    growth_rate = models.FloatField(default=0)
    added_on = models.DateTimeField(auto_now_add=True) 

    def __str__(self):
        return self.name

class GrowthHistory(models.Model):
    asset = models.ForeignKey(Asset,on_delete=models.CASCADE)
    invested_value = models.DecimalField(max_digits=12, decimal_places=2)
    current_value = models.DecimalField(max_digits=12,decimal_places=2)
    growth_rate = models.FloatField(default=0)
    added_on = models.DateTimeField(auto_now_add=True) 

class Liabilities(models.Model):
    TYPE_CHOICE = [
        ('home_loans','Home Loans'),
        ('education_loans','Education Loans'),
        ('car_loans','Car Loans'),
        ('other_personal_loans','Other Personal Loans'),
        ('business_loan','Business Loans'),
        ('product_purchase_loans','Product Purchase Loans (EMIs)'),
        ('payable_to_friends_family','Payable to Family or Friends'),
        ('others','Other Loans'),
    ]

    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=100,choices=TYPE_CHOICE)
    notes = models.CharField(max_length=255)
    total_amount = models.DecimalField(max_digits=12,decimal_places=2)
    installments = models.DecimalField(max_digits=12,decimal_places=2)
    added_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

assets/forms.py
from django import forms
from .models import Asset,Liabilities

class AssetForm(forms.ModelForm):
    class Meta:
        model = Asset
        fields = ['name','type','tenure','purpose','invested_value']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'type':forms.Select(attrs={'class':'form-control'}),
            'tenure':forms.Select(attrs={'class':'form-control'}),
            'purpose':forms.TextInput(attrs={'class':'form-control'}),
            'invested_value':forms.NumberInput(attrs={'class':'form-control'}),
            'current_value':forms.NumberInput(attrs={'class':'form-control'}),

        }
        
class LiabilityForm(forms.ModelForm):
    class Meta:
        model = Liabilities
        fields = ['name','type','notes','total_amount','installments']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'type':forms.Select(attrs={'class':'form-control'}),
            'notes':forms.TextInput(attrs={'class':'form-control'}),
            'total_amount':forms.NumberInput(attrs={'class':'form-control'}),
            'installments':forms.NumberInput(attrs={'class':'form-control'}),
        }

assets/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Asset,Liabilities, GrowthHistory
from .forms import AssetForm,LiabilityForm
from . import support_func
from core.models import UserProfile
from datetime import datetime
from django.db.models import Sum
from django.http import HttpResponseForbidden
from decimal import Decimal


# support functions
# deviations calculator
def dev_msg():
    nifty,mrkt_val,mrkt_sntim = support_func.deviator()
    analysis = {'nifty':nifty,'market_val':mrkt_val,'market_sentim':mrkt_sntim}
    # conclusion
    #print(mrkt_sntim,mrkt_val)
    if mrkt_val < 0 and mrkt_sntim < 0:
        # extreme low
        if mrkt_val < -11 and mrkt_sntim < -19:
            analysis['msg_head'] = 'Deeply Undervalued'
            analysis['msg_body'] = 'Aggressive SIP & lump-sum investments suggested.'
        else:
            analysis['msg_head'] = 'Undervalued'
            analysis['msg_body'] = 'Adequate SIP & lump-sum investments are suggested.'
    elif mrkt_val < 0 and mrkt_sntim > 0:
        analysis['msg_head'] = 'Market: Inexpensive | Sentiments: Greedy'
        analysis['msg_body'] = 'Cautious SIP investments only. Parking in liquid funds are suggested.'
    elif mrkt_val > 0 and mrkt_sntim < 0:
        analysis['msg_head'] = 'Market: Expensive | Sentiments: Fearful'
        analysis['msg_body'] = 'Moderate SIP investments only. Hybrid funds are suggested.'
    elif mrkt_val > 0 and mrkt_sntim > 0:
        # extreme high
        if mrkt_val > 11 and mrkt_sntim > 24:
            analysis['msg_head'] = 'Bubble Risk'
            analysis['msg_body'] = 'Reduce exposure, avoid new investments in equity funds.'
        else:
            analysis['msg_head'] = 'Overvalued'
            analysis['msg_body'] = 'Avoiding lump-sum and focusing on small SIPs suggested.'
    elif mrkt_val ==  0 and mrkt_sntim == 0:
        analysis['msg_head'] = 'Fair Value'
        analysis['msg_body'] = 'Balanced SIPs and small lump-sum investments suggested.'
    elif mrkt_val ==  0 and mrkt_sntim > 0:
        analysis['msg_head'] = 'Market: Fair | Sentiments: Greedy'
        analysis['msg_body'] = 'Moderate SIPs and avoiding lump-sum investments suggested.'
    elif mrkt_val ==  0 and mrkt_sntim < 0:
        analysis['msg_head'] = 'Market: Fair | Sentiments: Fearful'
        analysis['msg_body'] = 'Balanced SIP and lump-sum investments suggested.'
    elif mrkt_val >  0 and mrkt_sntim == 0:
        analysis['msg_head'] = 'Market: Expensive | Sentiments: Fair'
        analysis['msg_body'] = 'Focus on small SIPs and consider partial profit booking.'
    elif mrkt_val <  0 and mrkt_sntim == 0:
        analysis['msg_head'] = 'Market: Inexpensive | Sentiments: Fair'
        analysis['msg_body'] = 'Moderate SIPs and lump-sum investments suggested.'
    return analysis

# projected growth amount
def growth_prjct(assets):
    lin_total_crnt,lin_grwth,cmpd_total_crnt,cmpd_grwth = 0,0,0,0
    linears = ['debt_mf','fixed_deposit','others']
    for asset in assets:
        if asset.type in linears:
            lin_total_crnt += asset.current_value
            lin_grwth += asset.current_value * Decimal(asset.growth_rate)
        else:
            cmpd_total_crnt += asset.current_value
            cmpd_grwth += asset.current_value * Decimal(asset.growth_rate)
    # linear ogr (overall growth rate)
    try:
        lin_ogr = lin_grwth/ lin_total_crnt
    except ZeroDivisionError:
        lin_ogr = 0
    # compound ogr (overall growth rate)
    try:
        cmpd_ogr = cmpd_grwth / cmpd_total_crnt
    except ZeroDivisionError:
        cmpd_ogr = 0
    # calculate year-wise projected amount (linear & compound)
    grwth_prjctns = []
    for years in range(11):
        lin_prjct = lin_total_crnt * ( 1 + lin_ogr * years )
        if cmpd_ogr > 0:
            cmpd_prjct = cmpd_total_crnt * (1 + cmpd_ogr)**years
        else:
            #print(cmpd_ogr)
            cmpd_prjct = cmpd_total_crnt * (1 + cmpd_ogr * years) # linear projection for negative growth %
        grwth_prjctns.append(round(float(lin_prjct + cmpd_prjct),2))
        print(f'Linear growth for year {years}: {round(float(lin_prjct),2)}\nCompund growth for year {years}:{round(float( cmpd_prjct) ,2)}')
    return grwth_prjctns

# individual growth rate calculation
def cl_grwth(asset,current_value,linear=False):
    try:
        monthly_grwth =  (current_value - asset.current_value)/asset.current_value
        if linear:# linear growth rate
            yearly_grwth =  (monthly_grwth * 12) * 100
        else: # compound growth rate
            yearly_grwth = ((1 + monthly_grwth)**12 -1) * 100
        
        # checking for previous growth history
        gr_hist = GrowthHistory.objects.filter(asset = asset)
        if gr_hist and gr_hist.count() > 1:
            print('growth history is more than 1 ')
            historical_growth = sum(hist.growth_rate for hist in gr_hist)
            growth_num = gr_hist.count()
            yearly_grwth = (historical_growth + float(yearly_grwth)) /(growth_num + 1) # average of previous and now value
            # check if it contains historical data which is older than 1 year
            for hist in gr_hist:
                if hist.added_on.year <= datetime.now().year - 1 and hist.added_on.month <= datetime.now().month:
                    hist.delete()
        # return yearly growth rate
        return yearly_grwth
        
    except ZeroDivisionError:
        return 0

# asset update alerts
def update_alert():
    if datetime.now().day == 28:
        return True
    else:
        return False
# -----------------------------------------------

@login_required
def balance_sheet(request):
    assets = Asset.objects.filter(user=request.user)
    profile = UserProfile.objects.filter(user = request.user)
    liabilities = Liabilities.objects.filter(user=request.user)
    # obtain inflation data
    for data in profile:
        infltn = data.inflation
    # calculate overall growth %
    total_invst_val,total_grwth_val = 0,0
    for asset in assets:
        total_invst_val += asset.invested_value
        total_grwth_val += (asset.invested_value * Decimal(asset.growth_rate))
    try:
        overall_growth = float(total_grwth_val/total_invst_val)
    except ZeroDivisionError:
        overall_growth = 0
    # growth projections
    grwth_prjctn = growth_prjct(assets)
    this_year = int(datetime.now().year)
    grwth_label = [x for x in range(this_year,this_year + 11)]

    real_grwth = ((1 + (overall_growth/100)) / (1 + (infltn/100)) - 1) # inflation adjusted growth
    # banner logic
    analysis = dev_msg()
    # type-wise asset data
    type_totals = assets.values('type').annotate(total=Sum('current_value')).order_by('type')
    type_label = [Asset(type = entry['type']).get_type_display() for entry in type_totals]
    type_value = [float(entry['total']) for entry in type_totals]
    context = {
        'assets': assets,
        'overall_growth':round(overall_growth,2),
        'analysis':analysis,
        'growth_projection':grwth_prjctn[-1],
        'growth_labels':grwth_label,
        'growth_projections':grwth_prjctn,
        'inflation':infltn,
        'real_growth':round(real_grwth,2),
        'type_labels':type_label,
        'type_values':type_value if type_value else None,
        'update_alert':update_alert(),
        'liabilities':liabilities,
    }
    return render( request, 'assets/balance_sheet.html',context)

@login_required
def add_asset(request):
    if request.method == 'POST':
        form = AssetForm(request.POST)
        if form.is_valid():
            asset = form.save(commit=False)
            asset.user = request.user
            asset.current_value = asset.invested_value
            asset.save()
            return redirect ('assets:wealth')
    else:
        form = AssetForm()
        return render(request, 'assets/add_assets.html', {'form':form})

@login_required
def asset_view(request, asset_id):
    asset = get_object_or_404(Asset, id=asset_id)

    if request.method == 'POST':
        update_type = request.POST.get('update-type')
        update_value = Decimal(request.POST.get('new-value'))

        if str(update_type) == 'invested':
            try:
                value_diff = update_value - asset.invested_value
                asset.invested_value = update_value
                asset.current_value = asset.current_value + value_diff
                asset.save()
                return redirect('assets:asset-view', asset_id=asset.id)  # Redirect to the same page or another
            except ValueError:
                return HttpResponseForbidden("Invalid input. Please provide numeric values.")
        elif str(update_type) == 'current':
            linears = ['debt_mf','fixed_deposit','others']
            try:
                if asset.type in linears:
                    asset.growth_rate = round(cl_grwth(asset,update_value,True),2)
                else:
                    asset.growth_rate = round(cl_grwth(asset,update_value),2)               
                asset.current_value = update_value
                asset.save()
                # update growth rate into growth history
                GrowthHistory.objects.create(asset = asset,invested_value = asset.invested_value,current_value = update_value,growth_rate = asset.growth_rate)
                print('growth history updated ( new object created)')
                return redirect('assets:asset-view', asset_id=asset.id)  # Redirect to the same page or another
            except ValueError:
                return HttpResponseForbidden("Invalid input. Please provide numeric values.")
        else:

assets/templates/assets/add_assets.html
{% extends 'base.html' %}
{% block title %}Add Asset{% endblock %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'assets/css/add_assets.css' %}?v=2">
<script src="{% static 'assets/js/add_assets.js' %}?v=9"></script>
<div class="center-wrapper">
    <div class="form-container">
        <h2>Add Assets</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Add Asset</button>
            <a href="{% url 'expense:dashboard' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</div>

{% endblock %}

assets/templates/assets/add_liability.html
{% extends 'base.html' %}
{% block title %}Add Liability{% endblock %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'assets/css/add_assets.css' %}?v=2">
<script src="{% static 'assets/js/add_assets.js' %}?v=9"></script>
<div class="center-wrapper">
    <div class="form-container">
        <h2>Add Liability</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Add Liability</button>
            <a href="{% url 'expense:dashboard' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</div>

{% endblock %}

assets/templates/assets/assets_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Asset View{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'assets/css/asset_view.css' %}?v=3">

<div class="container">
    <header>
        <h1>{{ asset.name }}</h1>
    </header>

    <section class="asset-details">
        <p><strong>Type:</strong> {{ asset.get_type_display }}</p>
        <p><strong>Tenure:</strong> {{ asset.get_tenure_display }}</p>
        <p><strong>Purpose:</strong> {{ asset.purpose }}</p>
        <p><strong>Invested Value:</strong> ₹ {{ asset.invested_value }}</p>
        <p><strong>Current Value:</strong> ₹ {{ asset.current_value }}</p>
        <p><strong>Growth Percentage:</strong> {{ asset.growth_rate }}%</p>
    </section>

    <section class="update-section">
        <h3>Update Asset<br><sub>(Update this data only on a monthly basis to keep the accuracy of the calculations.)</sub></h3>
        
        <form method="post" action="{% url 'assets:asset-view' asset.id %}">
            {% csrf_token %}
            <label for="update-type">Update:</label>
            <select id="update-type" name="update-type">
                <option value="invested">Invested Amount</option>
                <option value="current">Current Value</option>
            </select>

            <label for="new-value">New Value:</label>
            <input type="number" name="new-value" id="new-value" required>

        <button type="submit" class="btn btn-primary">Update</button>
        <a href="{% url 'assets:delete-asset' asset.id %}" class="btn btn-danger">Delete Asset</a>
        </form>
    </section>
</div>
{% endblock %}

assets/templates/assets/balance_sheet.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Balance Sheet{% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}?v=5">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>
    <div class="banner">
        <div class="value">
            <h3>NIFTY50 Value</h3>
            <p>{{ analysis.nifty }}<br><sub>Points</sub></p>
        </div>
        <div class="value">
            <h3>Market Value</h3>
            <p>{{ analysis.market_val }}%<br><sub>Deviation</sub></p>
        </div>
        <div class="value">
            <h3>Market Sentiments</h3>
            <p>{{ analysis.market_sentim }}%<br><sub>Deviation</sub></p>
        </div>
        <div class="action-tip">
            <h3>{{ analysis.msg_head }}</h3>
            <p>{{ analysis.msg_body }}</p>
        </div>
    </div>
    <div class="growth-banner">
        <div class="value">
            <h3>Overall Growth</h3>
            <p>{{ overall_growth }} %</p>
        </div>
        <div class="value">
            <h3>Projected Growth</h3>
            <p>₹ {{ growth_projection }} <br><sub>( in 10 years)</sub></p>
        </div>
        <div class="value">
            <h3>Inflation Adjusted Growth</h3>
            <p>{{ real_growth }} % <br><sub>Inflation: {{ inflation }} %</sub></p>
        </div>
    </div>
    <div class="alert">
        {% if update_alert %}
            <h3>Assets Data Update Alert</h3>
            <p>Please update invested amount & current amount of your assets to maintain the accuracy of calculations.<br>Ignore if already done.</p>
        {% endif %}
    </div>
    <div class="content">
        <div class="visual-display">
            <div class="growth-chart">
                <h2>Wealth Projection</h2>
                <canvas id="assetGrowth"></canvas>>
            </div>
            <div class="assets-ratio">
                <h2>Wealth Distribution</h2>
                {% if type_values %}
                    <canvas id="wealth-distribution"></canvas>
                {% else %}
                    <p>Add assets to view wealth distribution.</p>
                {% endif %}
            </div>
        </div>

        <div class="asset-list">
            <h2>Assets</h2>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Invested Value</th>
                        <th>Current Value</th>
                        <th>Growth %</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for asset in assets %}
                    <tr>
                        <td>{{ asset.name }}</td>
                        <td>₹{{ asset.invested_value }}</td>
                        <td>₹{{ asset.current_value }}</td>
                        <td>{{ asset.growth_rate }}%</td>
                        <td><a href="{% url 'assets:asset-view' asset.id %}" class="view-button">View</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="asset-list">
            <h2>Liabilities</h2>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Installments</th>
                        <th>Total Amount</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for loan in liabilities %}
                    <tr>
                        <td>{{ loan.name }}</td>
                        <td>{{ loan.get_type_display }}</td>
                        <td>₹{{ loan.installments }}</td>
                        <td>₹{{ loan.total_amount }}</td>
                        <td><a href="{% url 'assets:lib-view' loan.id %}" class="view-button">View</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            // Data for Activity Chart
            const activityChartCtx = document.getElementById('assetGrowth').getContext('2d');
            const activityData = {
                labels: {{ growth_labels| safe }}, // Example: Adjust dynamically | {{ date_list|safe }}
                datasets: [{
                    label: 'Wealth',
                    data: {{ growth_projections|safe }}, // Example data {{ count_list|safe }}
                    borderColor: '#4CAF50',
                    fill: false,
                    tension: 0.3
                }]
            };
    
            new Chart(activityChartCtx, {
                type: 'line',
                data: activityData,
                options: {
                    responsive: true,
                    plugins: {
                        legend: {
                            display: false
                        }
                    },
                    scales: {
                        x: {
                            title: {
                                display: true,
                                text: 'Years',
                                color:'#ffffff'
                            }
                        },
                        y: {
                            title: {
                                display: true,
                                text: 'Projected Wealth ( in ₹ )',
                                color:'#ffffff'
                            }
                        }
                    }
                }
            });
            // Doughnut chart for wealth distribution
            var ctx = document.getElementById('wealth-distribution').getContext('2d');
            var chart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: {{ type_labels|safe|default:"[]" }},
                    datasets: [{
                        data: {{ type_values|safe|default:"[]" }},
                        backgroundColor: [
                            '#c73554', '#257db7', '#349696', 
                            '#f5a623', '#a55eea', '#2ecc71', 
                            '#e74c3c', '#34495e', '#9b59b6', 
                            '#1abc9c'
                        ],
                        borderColor: [
                        'rgba(255, 99, 132, 1)', 
                        'rgba(54, 162, 235, 1)', 
                        'rgba(255, 206, 86, 1)', 
                        'rgba(255, 159, 64, 1)', 
                        'rgba(153, 102, 255, 1)', 
                        'rgba(46, 204, 113, 1)', 
                        'rgba(231, 76, 60, 1)', 
                        'rgba(52, 73, 94, 1)', 
                        'rgba(155, 89, 182, 1)', 
                        'rgba(26, 188, 156, 1)'
                        ],
                    }]
                },
                options: {
                    responsive: true,
                    cutout: '50%', 
                    plugins: {
                        legend: {
                            position: 'top',
                        },
                        tooltip: {
                            callbacks: {
                                label: function(tooltipItem) {
                                    var dataset = tooltipItem.chart.data.datasets[0];
                                    var total = dataset.data.reduce(function(previousValue, currentValue) {
                                        return previousValue + currentValue;
                                    }, 0);
                                    var currentValue = dataset.data[tooltipItem.dataIndex];
                                    var percentage = Math.floor(((currentValue / total )* 100) + 0.5); 
                                    return ' ' + percentage + '%'; 
                                }
                            }
                        },
                        datalabels: {
                            formatter: function(value, ctx) {
                                var total = 0;
                                ctx.chart.data.datasets[0].data.forEach(function(item) {
                                    total += item;
                                });
                                var percentage = (value/total * 100).toFixed(2) + '%';
                                return percentage;
                            },
                            color: '#fff',
                            anchor: 'center',
                            align: 'center'
                        }
                    }
                }
            });
        });
    
    </script>
{% endblock %}

assets/templates/assets/delete_asset.html
{% extends 'base.html' %}
{% block content %}
<div class="confirm-delete">
    <h2>Are you sure you want to delete "{{ asset.name }}"?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
        <a href="{% url 'assets:wealth' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
<style>
    .confirm-delete {
        text-align: center;
    }
    .btn-secondary {
    background-color: #6c757d;
    color: white;
    border: none;
    padding: 8px 12px;
    border-radius: 4px;
    cursor: pointer;
    }

    .btn-secondary:hover {
    background-color: #5a6268;
    }
    .btn-danger {
    text-align: center;
    background-color: #dc3545;
    color: white;
    border: none;
    padding: 8px 12px;
    border-radius: 4px;
    cursor: pointer;
    }

    .btn-danger:hover {
    background-color: #c82333;
    }

</style>
{% endblock %}

assets/templates/assets/liability_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Liability View{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'assets/css/asset_view.css' %}?v=2">

<div class="container">
    <header>
        <h1>{{ liability.name }}</h1>
    </header>

    <section class="asset-details">
        <p><strong>Type:</strong> {{ liability.get_type_display }}</p>
        <p><strong>Notes:</strong> {{ liability.notes }}</p>
        <p><strong>Installments:</strong> ₹ {{ liability.installments }}</p>
        <p><strong>Total Amount:</strong> ₹ {{ liability.total_amount }}</p>
    </section>

    <section class="update-section">
        <h3>Update Liability</h3>
        
        <form method="post" action="{% url 'assets:lib-view' liability.id %}">
            {% csrf_token %}
            <label for="update-type">Update:</label>
            <select id="update-type" name="update-type">
                <option value="emi">Installments</option>
                <option value="total">Total Amount</option>
                <option value="notes">Notes</option>
            </select>

            <label for="new-value">New Value:</label>
            <input name="new-value" id="new-value" required>

        <button type="submit" class="btn btn-primary">Update</button>
        <a href="{% url 'assets:delete-lib' liability.id %}" class="btn btn-danger">Delete Liability</a>
    </form>
</div>
{% endblock %}